name: Auto Merge PRs

on:
  pull_request:
    types: [opened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Auto Merge PR
        uses: pascalgn/automerge-action@v0.15.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}